# Generated by ChatGPT on 2026-03-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_center', '0012_appointment_visit_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHCReimbursementClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('pending_accounts_verification', 'pending_accounts_verification'), ('approved', 'approved'), ('rejected', 'rejected'), ('reimbursed', 'reimbursed')], default='submitted', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phc_reimbursement_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PHCReimbursementAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.TextField(blank=True, default='')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='health_center.phcreimbursementclaim')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phc_reimbursement_audit_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
