# Generated by Django 3.1.5 on 2026-04-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0018_phc_reimbursement_claim_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='items',
            field=models.ManyToManyField(through='health_center.RequisitionItem', to='health_center.All_Medicine'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='health_center.appointment'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phc_visits', to='health_center.doctor'),
        ),
    ]
